name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Check codestyle
        run: git ls-files *.{cpp,h} | xargs clang-format -i && git diff --exit-code

      - name: pre-making
        run: sudo apt-get -y install libgtk-3-dev libwebkit2gtk-4.0-dev
      - name: tests
        run: make test
      - name: Build application
        run: make